quarkus.rest-client.products-api.url=http://localhost:8081

# Habilitar log do SQL gerado
quarkus.log.console.level=DEBUG
quarkus.log.category."io.quarkus.hibernate.orm".level=DEBUG

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/ORDER



